# Generated by Django 3.2.8 on 2021-10-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
    ]
