# Generated by Django 3.2.8 on 2021-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='https://www.legalgraphicworks.com/wp-content/plugins/bb-plugin/img/no-image.png', max_length=250),
        ),
    ]
